scripts/coverage: small cleanup

diff --git a/scripts/coverage b/scripts/coverage
--- a/scripts/coverage
+++ b/scripts/coverage
@@ -6,7 +6,7 @@ BRIDGE_INCLUDES="${SRC_DIR}/bridge/*.ts"
 COMMON_INCLUDES="${SRC_DIR}/common/*.ts"
 INTERNAL_INCLUDES="${SRC_DIR}/internal/**/*.ts"
 
-run_tests () {
+main_test () {
   c8 \
     --reports-dir $REPORTS_DIR \
     --include "${SRC_INCLUDES}" \
@@ -16,7 +16,7 @@ run_tests () {
     ts-mocha -p test/tsconfig.json
 }
 
-run_report () {
+main_report () {
     c8 report \
       --reports-dir $REPORTS_DIR \
       --include "${SRC_INCLUDES}" \
@@ -26,13 +26,15 @@ run_report () {
       --reporter=text-lcov > $REPORTS_DIR/lcov.info
 }
 
-case $1 in
-  "test")
-    run_tests
-    ;;
-  "report")
-    run_report
-    ;;
-  *)
-    echo "please pass either \"test\" or \"report\""
+command=$1
+case $command in
+    *)
+        shift
+        main_${command} $@
+        if [ $? = 127 ]; then
+            echo "Error: '$command' is not a known command." >&2
+            echo "       Allowed commands: test, report" >&2
+            exit 1
+        fi
+        ;;
 esac
