scripts: unify more scripts [ci notest]

diff --git a/scripts/sdk-tests b/scripts/sdk-tests
--- a/scripts/sdk-tests
+++ b/scripts/sdk-tests
@@ -6,7 +6,7 @@ BRIDGE_INCLUDES="${SRC_DIR}/bridge/*.ts"
 COMMON_INCLUDES="${SRC_DIR}/common/*.ts"
 INTERNAL_INCLUDES="${SRC_DIR}/internal/**/*.ts"
 
-main_test () {
+coverage_test () {
   c8 \
     --reports-dir $REPORTS_DIR \
     --include "${SRC_INCLUDES}" \
@@ -16,7 +16,7 @@ main_test () {
     ts-mocha -p test/tsconfig.json
 }
 
-main_report () {
+coverage_report () {
     c8 report \
       --reports-dir $REPORTS_DIR \
       --include "${SRC_INCLUDES}" \
@@ -26,6 +26,25 @@ main_report () {
       --reporter=text-lcov > $REPORTS_DIR/lcov.info
 }
 
+main_test () {
+  ts-mocha -p test/tsconfig.json
+}
+
+main_coverage () {
+  command=$1
+  case $command in
+      *)
+          shift
+          coverage_${command} $@
+          if [ $? = 127 ]; then
+              echo "Error: coverage '$command' is not a known command." >&2
+              echo "       Allowed commands: test, report" >&2
+              exit 1
+          fi
+          ;;
+  esac
+}
+
 command=$1
 case $command in
     *)
@@ -33,7 +52,7 @@ case $command in
         main_${command} $@
         if [ $? = 127 ]; then
             echo "Error: '$command' is not a known command." >&2
-            echo "       Allowed commands: test, report" >&2
+            echo "       Allowed commands: test, coverage" >&2
             exit 1
         fi
         ;;
